type: secure-aws-lambda
version: 1.0.0
core: 0.2.x

description: AWS Lambda Serverless Component Secured by Puresec FunctionShield
license: ????
author: Puresec <support@puresec.io> (https://puresec.io)
repository: github:puresec/secure-aws-lambda

inputTypes:
  policy:
    type: object
    default: {}
    displayName: FunctionShield policy
    description: Enforced FunctionShield policy
    example:
      policy:
        outbound_connectivity: block
        read_write_tmp: alert
        create_child_process: alert
  token:
    type: string
    required: true
    displayName: FunctionShield Token
    description: To get a token please visit https://www.puresec.io/function-shield-token-form
    example: dmVyeWxvbmdyYW5kb21kYXRh
  version:
    type: string
    required: true
    default: 1.0.x
    displayName: FunctionShield package version
    description: Version of @puresec/funtion-shield package to install for this function
    example: 1.0.2
